# Copyright 2021 Canonical Ltd.
# See LICENSE file for licensing details.

options:
  port:
    type: int
    default: 8081
    description: HTTP port
  manager-port:
    type: int
    default: 8080
    description: Management port
