# Copyright 2023 Canonical Ltd.
# See LICENSE file for licensing details.

options:
  port:
    type: int
    default: 8081
    description: HTTP port
  manager-port:
    type: int
    default: 8080
    description: Management port
  security-policy:
    type: string
    default: "privileged"
    description: >
      Specify the security policy to enforce in user workloads. The allowed values are `privileged`, `baseline`, and `restricted`.

      This option changes the label that is added to all workloads in the profile's namespace. For more information, refer to: https://kubernetes.io/docs/concepts/security/pod-security-standards/
